Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -61,6 +61,16 @@ function run_grunt() {
   fi
 }
 
+function run_bower() {
+  cd $BUILD_DIR
+  HOME="$BUILD_DIR" $CACHE_TARGET_DIR/bower/bin/bower install 2>&1 | indent
+
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Bower production task failed"
+    exit 1
+  fi
+}
+
 function manifest_versions() {
   curl "http://${S3_BUCKET}.s3.amazonaws.com/manifest.${1}" -s -o - | tr -s '\n' ' '
 }
@@ -188,6 +198,7 @@ export CPPPATH="$INCLUDE_PATH"
 echo "-----> Installing dependencies with npm"
 run_npm "install --production"
 run_npm "rebuild"
+run_bower
 echo "Dependencies installed" | indent
 
 echo "-----> Compiling Assets"
